site_name: Python Smart Contracts
nav:
    - 'prelude.md'
    - 'env.md'
    - 'helloworld.md'
    - 'action.md'
    - 'notify.md'
    - 'database.md'
    - 'crypto.md'
    - 'common.md'
    - 'codon.md'
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
